repos:
  # 1. Faz linting e correções adicionais no final
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.9.3"
    hooks:
      - id: "ruff"
        args: [--fix]

      - id: ruff-format

  # bandit linter
  - repo: "https://github.com/PyCQA/bandit"
    rev: "1.8.2"
    hooks:
      - id: "bandit"
        name: "bandit"
        description: "Bandit is a tool for finding common security issues in Python code"
        entry: "bandit"
        language: "python"
        language_version: "python3"
        types: ["python"]
        require_serial: true
        args:
          - "-c"
          - "pyproject.toml"
          - "-o"
          - "bandit_results.html"
          - "-f"
          - "html"
        additional_dependencies: ["bandit[toml]"]

  # - repo: "https://github.com/PyCQA/flake8"
  #   rev: "7.0.0"
  #   hooks:
  #     - id: "flake8"
  #       entry: pflake8
  #       additional_dependencies:
  #         [
  #           "pyproject-flake8",
  #           "flake8-docstrings",
  #           "flake8-bandit",
  #           "flake8-bugbear",
  #         ]
